In [1]:
!pip install ntscraper

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ntscraper in c:\users\hp\appdata\roaming\python\python311\site-packages (0.3.12)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from ntscraper) (2.31.0)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from ntscraper) (4.12.2)
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (from ntscraper) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->ntscraper) (2.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->ntscraper) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->ntscraper) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->ntscraper) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->ntscraper) (2023.7.22)

In [2]:
final_my_tweet= ['Tweets',
 '@balen_shah1 Good 😊😊',
 '@belakoboli khasai kei gareko ta xainan balen dai le yeti bidi jholey tarika le raja sanga comapre nagareko vaye hu… https://t.co/UOBy38KitJ',
 'The master of corruption of my country: The President, Prime Minister, Minister, MP, MLA, Mayor and even the Ward C… https://t.co/tOaO6Vydvu',
 '@belakoboli One of the extremely rare occasions where I happen to agree with this guy, even if partially. Although… https://t.co/zq3ORYvsvy',
 'Balen during weekends! 🤔\n\n https://t.co/OS44uOMGjE',
 'Balen and Sampang effect in federal elections https://t.co/6lC0qdePoG via @TheAnnaExpress',
 '@machiel1 @albertheijn Whut? Balen!',
 '@BaldipChauhan @RabindraMishra Rabindra Mishra will never win. He ended his political career the moment he decided… https://t.co/9RucvbpnUm',
 '@balen_shah1 Proud of you @ShahBalen',
 'balen’s wife… i wasn’t familiar with his game',
 '@sanghiyawtie Balen is leading the metropolis while serving. k bhaneko mijyu yesto?😩',
 '@balen_shah1 Really nice pict thank you  keep going sir please I from Boston please 🙏',
 'RT @RoyalFamily: His Majesty The King gives a\xa0personal\xa0declaration at today’s Accession Council, where he was formally proclaimed King Char…',
 '@balen_shah1 Beautiful',
 '@kandeldai Jealousy against Balen',
 'RT @sanzinme: Hait #Balen 🔥🔥 https://t.co/QWjkBRUnFT',
 'Songs of LANY 🎵 🎶',
 'ELECTION 2022\n\n"Rise of independent candidates like Balen and Sampang at the local level has paved the path for sev… https://t.co/mmJVv2q645',
 '@balen_shah1 Fake Acount',
 '@balen_shah1 Good 🙏🙏',
 '@balen_shah1 Thank.',
 "RT @ShellenbergerMD: That's not the end of the story, of course. Farmers can fight back. We can show solidarity with them. \n\nIn Sri Lanka t…",
 "So nicely expressed ! Balen and the team should heed on the author's feedback. \n\n@kathmandupost, hilarious is the m… https://t.co/gwW3hknZHY",
 '@balen_shah1 Hero of nation',
 '@rameshore Balen is able to deliver, because he is professional and free to take his own decisions, unfettered by c… https://t.co/VDWM4kjDO0',
 '@balen_shah1 rell time rell king i love ..my heart contact fell',
 '@juction4love Before Balen, the President and the Prime Minister showed zero and\nthinking👇 🤔 👌😋 \nSame photo 👇👇terro… https://t.co/3b3CCb8x3V',
 'Balen is no less than a great celebrity!\n#BalenSupporter ✌️',
 "RT @RaameshKoirala: Is Balen a DON?\nNO.\nHe deserves extra 'e'.\nWell DONE!\n🙏🙏🙏🙏🙏",
 "When you're hangry af at a momo pasal and the server is down so you can't even watch balen's dozer on tiktok https://t.co/2ripYTt0mO",
 'I wonder will rabindra misra accept balen as new king when monarchy gets back?🤔',
 'RT @SarcasmNpl: Nothing interesting, just Routiney pretending Balen to be the king. https://t.co/0urZ0GuvGX',
 '@balen_shah1 Is Balen compairing himself with the king.... OMG ,',
 'but is Balen a leader at all? Isn’t he a public servant? https://t.co/USTKazCR0T',
 '@balen_shah1 Great Job',
 'RT @RONBupdates: Kathmandu Metro Mayor Balen Shah gave his presence during Indra Jatra at Basantapur yesterday and huge crowd of people was…',
 'RT Emily Ratajkowski slays Ratajkowski wearing Knwls Halcyon Long-Sleeved Top, Knwls Halcyon Flared Leggings, Balen… https://t.co/MRSzQQp7iF',
 '@NirmalPrasai5 Nirmal jee, I still remember you arguing with me on Twitter during the Mayoral election, saying Bale… https://t.co/oEq8stvZfp',
 'RT @arundadhikary: अब अरु लाई ridicule गरेर भोट जितिदैन ! Those days are gone ! You must stand out on your own merit without belittling you…',
 'RT @LawaRashid: Summer dump https://t.co/doppzTbq0t',
 'versace bottega praga balen vuitton dior givenchy',
 "bALEN'S Craze is evidence of hunger for good leadership in Nepal",
 '@balen_shah1 Nice pic',
 'The Balen brothers blew through the competition winning the first annual 2A District Doubles Invite tournament! Con… https://t.co/jwrp7ffmct',
 '@Split_72 How do you make SO MANY LEVELS',
 '@ShashankGhimir8 @balen_shah1 It’s fan page 😁',
 'RT @NoNext_Question: The video shows people’s craze and support for Kathmandu Metropolis Mayor Balen Shah during Indra Jatra festival held…',
 '@balen_shah1 Great effort. Well-done Balen, salute you 🌹',
 '@balen_shah1 Really proud of you and shine like our king  birendra. Always think about our nepali people and I am h… https://t.co/eJSsC2caiQ',
 '@balen_shah1 Keep up the good work ☺️',
 'Balen turning into a revolution. https://t.co/ygiKnuzHfe',
 '@parajulippradip @balen_shah1 This is the pic of the decade ❣️',
 'RT @SamratSpeaks: Balen is making us dormant folks realize what a leader should be, something we never had so far. Never in my life had I s…',
 '@balen_shah1 Great work',
 'It’s not a purse. It’s a Balen.',
 '@Dipendra02468 @balen_shah1 So it has been warned',
 '@Anjita_pandey Thnak you. I willbe there. Balen ko sahar ma ni aainus.. https://t.co/zZx4DQXzJW',
 'RT @_bishab: Balen turning into a revolution. https://t.co/ygiKnuzHfe',
 '@ShahBalen 200-300 paid actor everyday follows balen tetro berojgar ni chaina hola ni free ma nara lagayera balen b… https://t.co/yfVtLqPdKe',
 '@dipeshrisal This is another extreme ..sure Balen realizes it. Also King B did not have Balen kind of personality -… https://t.co/U6rjUeEiso',
 '@balen_shah1 Great job 👏',
 '@bahunnaran Balen is not king 👑💯👑 ok ...',
 '@theomeereboer Shit. Balen',
 '@creo_music I will gladly play the triple a price of 60 United States dollars for a Creo game',
 'RT @drs1k: @juction4love Before Balen, the President and the Prime Minister showed zero and\nthinking👇 🤔 👌😋 \nSame photo 👇👇terrorist https://…',
 "@iRiskant_ @NS_online Blegh, da's balen. 💔",
 '@balen_shah1 nice pic ....go ahead balen ji']

In [6]:
import re

def get_normalize(text):
    text = re.sub(r'\&\w*;', '', text)
    text = re.sub('@[^\s]+', '', text)
    text = re.sub(r'\$\w*', '', text)
    return text

# Sample usage
j = 0
for i in final_my_tweet:
    final_my_tweet[j] = get_normalize(str(i))
    j += 1

final_my_tweet

['Tweets',
 ' Good 😊😊',
 ' khasai kei gareko ta xainan balen dai le yeti bidi jholey tarika le raja sanga comapre nagareko vaye hu… https://t.co/UOBy38KitJ',
 'The master of corruption of my country: The President, Prime Minister, Minister, MP, MLA, Mayor and even the Ward C… https://t.co/tOaO6Vydvu',
 ' One of the extremely rare occasions where I happen to agree with this guy, even if partially. Although… https://t.co/zq3ORYvsvy',
 'Balen during weekends! 🤔\n\n https://t.co/OS44uOMGjE',
 'Balen and Sampang effect in federal elections https://t.co/6lC0qdePoG via ',
 '  Whut? Balen!',
 '  Rabindra Mishra will never win. He ended his political career the moment he decided… https://t.co/9RucvbpnUm',
 ' Proud of you ',
 'balen’s wife… i wasn’t familiar with his game',
 ' Balen is leading the metropolis while serving. k bhaneko mijyu yesto?😩',
 ' Really nice pict thank you  keep going sir please I from Boston please 🙏',
 'RT  His Majesty The King gives a\xa0personal\xa0declaration at today’s Accession Council, where he was formally proclaimed King Char…',
 ' Beautiful',
 ' Jealousy against Balen',
 'RT  Hait #Balen 🔥🔥 https://t.co/QWjkBRUnFT',
 'Songs of LANY 🎵 🎶',
 'ELECTION 2022\n\n"Rise of independent candidates like Balen and Sampang at the local level has paved the path for sev… https://t.co/mmJVv2q645',
 ' Fake Acount',
 ' Good 🙏🙏',
 ' Thank.',
 "RT  That's not the end of the story, of course. Farmers can fight back. We can show solidarity with them. \n\nIn Sri Lanka t…",
 "So nicely expressed ! Balen and the team should heed on the author's feedback. \n\n hilarious is the m… https://t.co/gwW3hknZHY",
 ' Hero of nation',
 ' Balen is able to deliver, because he is professional and free to take his own decisions, unfettered by c… https://t.co/VDWM4kjDO0',
 ' rell time rell king i love ..my heart contact fell',
 ' Before Balen, the President and the Prime Minister showed zero and\nthinking👇 🤔 👌😋 \nSame photo 👇👇terro… https://t.co/3b3CCb8x3V',
 'Balen is no less than a great celebrity!\n#BalenSupporter ✌️',
 "RT  Is Balen a DON?\nNO.\nHe deserves extra 'e'.\nWell DONE!\n🙏🙏🙏🙏🙏",
 "When you're hangry af at a momo pasal and the server is down so you can't even watch balen's dozer on tiktok https://t.co/2ripYTt0mO",
 'I wonder will rabindra misra accept balen as new king when monarchy gets back?🤔',
 'RT  Nothing interesting, just Routiney pretending Balen to be the king. https://t.co/0urZ0GuvGX',
 ' Is Balen compairing himself with the king.... OMG ,',
 'but is Balen a leader at all? Isn’t he a public servant? https://t.co/USTKazCR0T',
 ' Great Job',
 'RT  Kathmandu Metro Mayor Balen Shah gave his presence during Indra Jatra at Basantapur yesterday and huge crowd of people was…',
 'RT Emily Ratajkowski slays Ratajkowski wearing Knwls Halcyon Long-Sleeved Top, Knwls Halcyon Flared Leggings, Balen… https://t.co/MRSzQQp7iF',
 ' Nirmal jee, I still remember you arguing with me on Twitter during the Mayoral election, saying Bale… https://t.co/oEq8stvZfp',
 'RT  अब अरु लाई ridicule गरेर भोट जितिदैन ! Those days are gone ! You must stand out on your own merit without belittling you…',
 'RT  Summer dump https://t.co/doppzTbq0t',
 'versace bottega praga balen vuitton dior givenchy',
 "bALEN'S Craze is evidence of hunger for good leadership in Nepal",
 ' Nice pic',
 'The Balen brothers blew through the competition winning the first annual 2A District Doubles Invite tournament! Con… https://t.co/jwrp7ffmct',
 ' How do you make SO MANY LEVELS',
 '  It’s fan page 😁',
 'RT  The video shows people’s craze and support for Kathmandu Metropolis Mayor Balen Shah during Indra Jatra festival held…',
 ' Great effort. Well-done Balen, salute you 🌹',
 ' Really proud of you and shine like our king  birendra. Always think about our nepali people and I am h… https://t.co/eJSsC2caiQ',
 ' Keep up the good work ☺️',
 'Balen turning into a revolution. https://t.co/ygiKnuzHfe',
 '  This is the pic of the decade ❣️',
 'RT  Balen is making us dormant folks realize what a leader should be, something we never had so far. Never in my life had I s…',
 ' Great work',
 'It’s not a purse. It’s a Balen.',
 '  So it has been warned',
 ' Thnak you. I willbe there. Balen ko sahar ma ni aainus.. https://t.co/zZx4DQXzJW',
 'RT  Balen turning into a revolution. https://t.co/ygiKnuzHfe',
 ' 200-300 paid actor everyday follows balen tetro berojgar ni chaina hola ni free ma nara lagayera balen b… https://t.co/yfVtLqPdKe',
 ' This is another extreme ..sure Balen realizes it. Also King B did not have Balen kind of personality -… https://t.co/U6rjUeEiso',
 ' Great job 👏',
 ' Balen is not king 👑💯👑 ok ...',
 ' Shit. Balen',
 ' I will gladly play the triple a price of 60 United States dollars for a Creo game',
 'RT   Before Balen, the President and the Prime Minister showed zero and\nthinking👇 🤔 👌😋 \nSame photo 👇👇terrorist https://…',
 "  Blegh, da's balen. 💔",
 ' nice pic ....go ahead balen ji']

In [8]:
import pandas as pd

tweets = {'tweets': final_my_tweet}
data = pd.DataFrame(tweets)
data

                                               tweets
0                                              Tweets
1                                             Good 😊😊
2    khasai kei gareko ta xainan balen dai le yeti...
3   The master of corruption of my country: The Pr...
4    One of the extremely rare occasions where I h...
..                                                ...
63                                        Shit. Balen
64   I will gladly play the triple a price of 60 U...
65  RT   Before Balen, the President and the Prime...
66                               Blegh, da's balen. 💔
67                     nice pic ....go ahead balen ji

[68 rows x 1 columns]

In [10]:
new_data = data.drop_duplicates(subset="tweets") #to drop retweets and repeated rows #subset is a keyword in pandas with column value as "Tweets" to indicate the column with duplicate text
new_data.to_csv('filtered_data.csv')
new_data

                                               tweets
0                                              Tweets
1                                             Good 😊😊
2    khasai kei gareko ta xainan balen dai le yeti...
3   The master of corruption of my country: The Pr...
4    One of the extremely rare occasions where I h...
..                                                ...
63                                        Shit. Balen
64   I will gladly play the triple a price of 60 U...
65  RT   Before Balen, the President and the Prime...
66                               Blegh, da's balen. 💔
67                     nice pic ....go ahead balen ji

[68 rows x 1 columns]

In [13]:
!pip install textblob

Defaulting to user installation because normal site-packages is not writeable
Collecting textblob
  Obtaining dependency information for textblob from https://files.pythonhosted.org/packages/02/07/5fd2945356dd839974d3a25de8a142dc37293c21315729a41e775b5f3569/textblob-0.18.0.post0-py3-none-any.whl.metadata
  Downloading textblob-0.18.0.post0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: nltk>=3.8 in c:\programdata\anaconda3\lib\site-packages (from textblob) (3.8.1)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (8.0.4)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (2022.7.9)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (4.65.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk>=3.8->textblob) (0.4.6)
Downloading textblob-0.18.0.post0-py3-none-any.whl (626 kB)
   ---------------------------------------- 0.0/626.3 kB ? eta -:--:--
   - -------------------------------------- 30.7/626.3 kB 1.4 MB/s eta 0:00:01
   ----- --------------------------------- 92.2/626.3 kB 880.9 kB/s eta 0:00:01
   --------- ---------------------------- 153.6/626.3 kB 919.0 kB/s eta 0:00:01
   --------------- ------------------------ 235.5/626.3 kB 1.2 MB/s eta 0:00:01
   -------------------- ------------------- 327.7/626.3 kB 1.3 MB/s eta 0:00:01
   --------------------------------- ------ 522.2/626.3 kB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 626.3/626.3 kB 1.8 MB/s eta 0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.18.0.post0

In [14]:
from textblob import TextBlob
import pandas as pd

# Assuming 'new_data' is already created and contains a column 'tweets'
new_data[['Polarity', 'Subjectivity']] = new_data['tweets'].apply(
    lambda x: pd.Series(TextBlob(x).sentiment))

# Display the dataframe with the new columns
new_data

                                               tweets  Polarity  Subjectivity
0                                              Tweets      0.00         0.000
1                                             Good 😊😊      0.70         0.600
2    khasai kei gareko ta xainan balen dai le yeti...      0.00         0.000
3   The master of corruption of my country: The Pr...      0.00         0.000
4    One of the extremely rare occasions where I h...      0.10         0.600
..                                                ...       ...           ...
63                                        Shit. Balen     -0.20         0.800
64   I will gladly play the triple a price of 60 U...      0.05         0.700
65  RT   Before Balen, the President and the Prime...      0.00         0.125
66                               Blegh, da's balen. 💔      0.00         0.000
67                     nice pic ....go ahead balen ji      0.60         1.000

[68 rows x 3 columns]

In [15]:
new_data.to_csv('filtered_data.csv')

In [16]:
y = new_data['Polarity']
positive = 0
negative = 0
neutral = 0

for a in y:
    if a>0:
     positive=positive+1
    elif a<0:
     negative=negative+1
    else:
     neutral=neutral+1
numberOfTweetsAnalysed= positive+negative+neutral
print('Number of Tweets Analysed = '+str(numberOfTweetsAnalysed))
print('Positive tweets = '+str(positive))
print('Negative tweets = '+str(negative))
print('Neutral tweets = '+str(neutral))

Number of Tweets Analysed = 68
Positive tweets = 31
Negative tweets = 5
Neutral tweets = 32

In [17]:
df1 = new_data[new_data['Polarity'] > 0]
df1['sentiment'] ='Positive'
df2 = new_data[new_data['Polarity'] < 0]
df2['sentiment'] ='Negative'
df3 = new_data[new_data['Polarity'] == 0]
df3['sentiment'] ='Neutral'

new_data = pd.concat([df1,df2,df3]).sample(frac = 1)
new_data

C:\Users\HP\AppData\Local\Temp\ipykernel_19352\1103267366.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['sentiment'] ='Positive'
C:\Users\HP\AppData\Local\Temp\ipykernel_19352\1103267366.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['sentiment'] ='Negative'
C:\Users\HP\AppData\Local\Temp\ipykernel_19352\1103267366.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['sentiment'] ='Neutral'

,tweets,Polarity,Subjectivity,sentiment
43,Nice pic,0.6000,1.00,Positive
15,Jealousy against Balen,0.0000,0.00,Neutral
37,RT Emily Ratajkowski slays Ratajkowski wearing...,0.5000,0.50,Positive
60,This is another extreme ..sure Balen realizes...,0.2375,0.95,Positive
36,RT Kathmandu Metro Mayor Balen Shah gave his ...,0.4000,0.90,Positive
...,...,...,...,...
22,"RT That's not the end of the story, of course...",0.0000,0.00,Neutral
2,khasai kei gareko ta xainan balen dai le yeti...,0.0000,0.00,Neutral
3,The master of corruption of my country: The Pr...,0.0000,0.00,Neutral
24,Hero of nation,0.0000,0.00,Neutral
55,It’s not a purse. It’s a Balen.,0.0000,0.00,Neutral